import { Hono } from 'hono';
import { Bindings, Variables } from '../types';
import { getDb } from '../db';
import { users } from '../db/schema';
import { eq } from 'drizzle-orm';
import { getValidSpotifyToken } from '../services/spotify';

export const playlists = new Hono<{ Bindings: Bindings; Variables: Variables }>();

playlists.post('/splice', async (c) => {
  const userId = c.get('userId');
  const env = c.env;
  const db = getDb(env.DATABASE_URL);

  const body = await c.req.json();
  const trackIds: string[] = body.trackIds;
  const playlistName: string = body.name || '6Stats DNA Spliced Playlist';

  if (!trackIds || trackIds.length === 0) {
    return c.json({ error: 'No track IDs provided' }, 400);
  }

  // 1. Get user's Spotify ID
  const userRows = await db.select().from(users).where(eq(users.id, userId)).limit(1);
  const user = userRows[0];
  if (!user || !user.spotifyUserId) {
    return c.json({ error: 'User not found or no Spotify ID' }, 404);
  }

  // 2. Get valid access token
  const token = await getValidSpotifyToken(userId, db, env);

  // 3. Create playlist
  const createRes = await fetch(`https://api.spotify.com/v1/users/${user.spotifyUserId}/playlists`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      name: playlistName,
      description: 'Automatically generated by 6Stats Analytics Playground',
      public: false
    })
  });

  if (!createRes.ok) {
    const text = await createRes.text();
    console.error('Failed to create playlist:', text);
    return c.json({ error: 'Failed to create playlist on Spotify' }, 500);
  }

  const playlist = await createRes.json() as { id: string; external_urls: { spotify: string } };

  // 4. Add tracks
  const uris = trackIds.map(id => `spotify:track:${id}`);
  const addRes = await fetch(`https://api.spotify.com/v1/playlists/${playlist.id}/tracks`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({ uris })
  });

  if (!addRes.ok) {
    const text = await addRes.text();
    console.error('Failed to add tracks:', text);
    return c.json({ error: 'Failed to add tracks to playlist' }, 500);
  }

  return c.json({ 
    success: true, 
    playlistId: playlist.id,
    url: playlist.external_urls.spotify
  });
});
